version: "3.9"

networks:
  micro_network:

volumes:
  data:
  redisdata:

services:
#  nacos:
#    image: nacos/nacos-server:latest
#    ports:
#      - "8848:8848"
#    environment:
#      - "JVM_XMS=256m"
#      - "JVM_XMX=256m"
#      - "MODE=standalone"
#    networks:
#      - micro_network
#
#  mysql:
#    image: mysql:5.7
#    ports:
#      - "3306:3306"
#    networks:
#      - micro_network
#    volumes:
#      - data:/var/lib/mysql
#      - ./micro.sql:/docker-entrypoint-initdb.d/micro.sql
#    environment:
#      - "MYSQL_ROOT_PASSWORD=123456"
#      - "MYSQL_DATABASE=micro"
#
#  redis:
#    image: redis:latest
#    ports:
#      - "6379:6379"
#    networks:
#      - micro_network
#    volumes:
#      - redisdata:/data
#
#  nginx:
#    image: nginx:1.21.1
#    ports:
#      - "8080:8080"
#    networks:
#      - micro_network
#    volumes:
#      - ./admin-dist:/usr/share/nginx/html:ro

#  admins:
#    build:
#      context: ./images/admin
#      dockerfile: Dockerfile
#    ports:
#      - "8980:8980"
#    depends_on:
#      - mysql
#      - nacos
#      - redis

#  category:
#    build:
#      context: ./images/category
#      dockerfile: Dockerfile
#    ports:
#      - "8981:8981"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
  gateway:
    build:
      context: ./images/gateway
      dockerfile: Dockerfile
    ports:
      - "9998:9999"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  users:
#    build:
#      context: ./images/users
#      dockerfile: Dockerfile
#    ports:
#      - "8982:8982"
#    depends_on:
#      - mysql
#      - nacos
#      - redis
#
#  videos:
#    build:
#      context: ./images/videos
#      dockerfile: Dockerfile
#    ports:
#      - "8983:8983"
#    depends_on:
#      - mysql
#      - nacos
#      - redis