server:
  port: 8980

spring:
  application:
    name: API-ADMIN
  cloud:
    nacos:
      server-addr: localhost:8848
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.0.108:3306/micro?characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
  redis:
    host: 192.168.0.108
    port: 6379


mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: edu.ustc.entity


logging:
  level:
    edu.ustc.dao: debug
